version: '3.8'

services:
  sales-crew-api:
    image: ghcr.io/tiagolau/sales-crew-api:latest
    restart: unless-stopped
    environment:
      PORT: 8000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    networks:
      - traefik-public
    labels:
      traefik.enable: "true"
      traefik.http.routers.sales-crew.rule: "Host(`api-torre.rhinocrm.com.br`)"
      traefik.http.routers.sales-crew.entrypoints: "websecure"
      traefik.http.routers.sales-crew.tls: "true"
      # Removendo resolver especifico para evitar erros, vamos usar o padrao (Ignore SSL no N8N resolve)
      # traefik.http.routers.sales-crew.tls.certresolver: "levin"
      traefik.http.services.sales-crew.loadbalancer.server.port: "8000"

networks:
  traefik-public:
    external: true
